image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main # ветка git

build: off  # для использования своего скрипта сборки

install:
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &

build_script:
  - chmod +x gradlew # предоставление прав на запуск файла gradlew
  # запуск тестов, параметр -Dselenide.headless=true отключает графический интерфейс
  # флаг --info позволяет выводить больше информации
  - ./gradlew test -Dselenide.headless=true --info